service:
  name: Congestion Tax Calculator
  description: Congestion Tax Calculator
  version: 0.0.1
  url:
    base: /api
    docs: /docs

server:
  host: localhost
  port: 3000

vehicles:
  types:
    - Motorcycle
    - Car
    - Tractor
    - Emergency
    - Diplomat
    - Foreign
    - Militar

rules:
  - city: Gothenburg
    tollFreeVehicles:
      - Motorcycle
      - Tractor
      - Emergency
      - Diplomat
      - Foreign
      - Militar
    tollFreeDayBeforePublicHolidays: true
    tollFreeWeekends: true
    maxFeePerDay: 60
    freeMonths:
      - 7
    fees:
      - start: 06:00
        end: 06:29
        fee: 8
      - start: 06:30
        end: 06:59
        fee: 13
      - start: 07:00
        end: 07:59
        fee: 18
      - start: 08:00
        end: 08:29
        fee: 13
      - start: 08:30
        end: 14:59
        fee: 8
      - start: 15:00
        end: 15:29
        fee: 13
      - start: 15:30
        end: 16:59
        fee: 18
      - start: 17:00
        end: 17:59
        fee: 13
      - start: 18:00
        end: 18:29
        fee: 8
      - start: 18:30
        end: 05:59
        fee: 0

publicHolidays:
  - '2013-01-01'
  - '2013-03-28'
  - '2013-03-29'
  - '2013-04-01'
  - '2013-04-30'
  - '2013-05-01'
  - '2013-05-08'
  - '2013-05-09'
  - '2013-06-05'
  - '2013-06-06'
  - '2013-06-21'
  - '2013-11-01'
  - '2013-12-24'
  - '2013-12-25'
  - '2013-12-26'
  - '2013-12-31'
